apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-service
  template:
    metadata:
      labels:
        app: java-service
    spec:
      containers:
        - name: java-service
          image: romansamoylenko/java-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
            - containerPort: 9090
          env:
            - name: SPRING_APPLICATION_NAME
              value: "job-platform"
            - name: SERVER_PORT
              value: "8080"
            - name: GRPC_PORT
              value: "9090"
            - name: KAFKA_BROKERS
              value: "kafka-service:9092"
            - name: KAFKA_TOPIC
              value: "job_requests"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/jobsdb"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres"
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: "org.postgresql.Driver"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
