apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres-deployment.yaml
  - postgres-service.yaml
  - kafka-deployment.yaml
  - kafka-service.yaml
  - java-deployment.yaml
  - java-service.yaml
  - go-deployment.yaml
  - nginx-deployment.yaml
  - nginx-service.yaml
  - nginx-config.yaml
